# yamllint 設定
---
extends: default

rules:
  # 行長制限を緩和（GitHub Actionsのrunステップで長いコマンドが必要なため）
  line-length:
    max: 200
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # document-startは任意（---なしでも許可）
  document-start: disable

  # truthyの値を緩和（on/offも許可 - GitHub Actionsで使用）
  truthy:
    allowed-values: ["true", "false", "on", "off"]

  # インデントは2スペース
  indentation:
    spaces: 2
    indent-sequences: true

  # コメント前のスペースを緩和
  comments:
    min-spaces-from-content: 1
